window.TRIP = {
  title: "The Montenegro Tapes",
  dates: "5–10 сентября 2026",
  runtime: "6 дней",
  km: "~650 км",
  mixtape: [
    { n: "A1", title: "Born to Run", artist: "Bruce Springsteen" },
    { n: "A2", title: "There Is a Light That Never Goes Out", artist: "The Smiths" },
    { n: "A3", title: "Fade Into You", artist: "Mazzy Star" },
    { n: "A4", title: "Nightswimming", artist: "R.E.M." },
    { n: "A5", title: "Atmosphere", artist: "Joy Division" },
    { n: "B1", title: "Roads", artist: "Portishead" },
    { n: "B2", title: "Holocene", artist: "Bon Iver" },
    { n: "B3", title: "Fast Car", artist: "Tracy Chapman" },
    { n: "B4", title: "Love", artist: "The Smashing Pumpkins" },
    { n: "B5", title: "End of the Line", artist: "Traveling Wilburys" },
  ],
  photos: {
    road: "images/hero.jpg",
    kotor: "images/kotor.jpg",
    bay: "images/perast.jpg",
    mountain: "images/mountain.jpg",
    lake: "images/lake.jpg",
    canyon: "images/canyon.jpg",
    pass: "images/durmitor.jpg",
    forest: "images/forest.jpg",
    night: "images/night.jpg",
    village: "images/meadow.jpg",
    mist: "images/mist.jpg",
    durmitor: "images/durmitor.jpg",
    perast: "images/perast.jpg",
  },
  overview: {
    id: "overview",
    color: "#c45c26",
    title: "Петля, которую не перезаписать",
    slug: "SIDE A · ВЕСЬ ТРЕК · БЕЗ ПЕРЕМОТКИ",
    quote: "Аэропорт. Город. Залив. Горы. Снова город. Снова небо.",
    summary:
      "Шесть точек, как имена на вкладыше. Здесь карта не гонится за нами — только показывает, куда мы вообще собирались уехать. Дальше, по дням, уже пойдёт серпантин.",
    points: [
      {
        id: "ov-tgd",
        n: "01",
        name: "Аэропорт",
        place: "TGD · Подгорица",
        lat: 42.3594,
        lng: 19.2519,
      },
      {
        id: "ov-pg",
        n: "02",
        name: "Подгорица",
        place: "первая ночь",
        lat: 42.4415,
        lng: 19.262,
      },
      {
        id: "ov-kotor",
        n: "03",
        name: "Котор",
        place: "залив, который останется",
        lat: 42.4247,
        lng: 18.7712,
      },
      {
        id: "ov-park",
        n: "04",
        name: "Нацпарк",
        place: "Дурмитор · Жабляк",
        lat: 43.1547,
        lng: 19.1231,
      },
      {
        id: "ov-pg2",
        n: "05",
        name: "Подгорица",
        place: "последняя ночь",
        lat: 42.4415,
        lng: 19.262,
      },
      {
        id: "ov-out",
        n: "06",
        name: "Аэропорт",
        place: "вылет ~22:00",
        lat: 42.3594,
        lng: 19.2519,
      },
    ],
  },
  days: [
    {
      id: "sep5",
      date: "5 сентября",
      weekday: "суббота",
      hwy: "01",
      track: "A1",
      slug: "INT. АЭРОПОРТ — ПОСЛЕДНЯЯ НОЧЬ ПЕРЕД ПЕРВОЙ",
      title: "Тишина до первой песни",
      quote: "Кассета ещё не крутится. Мы уже внутри.",
      tagline: "Don't walk away in silence.",
      tone: "night",
      photo: "night",
      caption: "golden hour обещан на завтра",
      summary:
        "21:20 — касание полосы. Город держит дыхание. Машину берём сегодня: утро принадлежит дороге, а не очереди.",
      drive: "Подгорица",
      hours: "ночь",
      color: "#c45c26",
      route: [
        [42.3594, 19.2519],
        [42.4415, 19.262],
      ],
      stops: [
        {
          id: "airport",
          name: "Аэропорт Подгорица (TGD)",
          time: "21:20",
          dur: "прилёт",
          kind: "arrive",
          lat: 42.3594,
          lng: 19.2519,
          note: "Первый вдох чужого воздуха. С этой минуты всё будет вспоминаться в прошедшем — только чуть позже.",
          maps: "https://www.google.com/maps/search/?api=1&query=Podgorica+Airport",
        },
        {
          id: "car",
          name: "Забрать машину",
          time: "вечер",
          dur: "сейчас, не утром",
          kind: "tip",
          lat: 42.3594,
          lng: 19.2519,
          note: "Не оставляй на утро то, без чего утро не начнётся. С 6-го полоса уже не взлётная — серпантин на Котор.",
          maps: "https://www.google.com/maps/search/?api=1&query=car+rental+Podgorica+Airport",
        },
        {
          id: "pg-stay",
          name: "Ночёвка в Подгорице",
          time: "ночь",
          dur: "5–6 сен",
          kind: "sleep",
          lat: 42.4415,
          lng: 19.262,
          note: "Vukosava Božovića bb, 81000. Короткая ночь, как пауза между треками. Завтра — вода.",
          maps: "https://www.google.com/maps/search/?api=1&query=Vukosava+Bo%C5%BEovi%C4%87a+bb+Podgorica",
        },
      ],
    },
    {
      id: "sep6",
      date: "6 сентября",
      weekday: "воскресенье",
      hwy: "02",
      track: "A2",
      slug: "EXT. КОТОРСКИЙ ЗАЛИВ — ДЕНЬ, КОТОРЫЙ ОСТАНЕТСЯ",
      title: "Вода помнит нас раньше",
      quote: "You can never go home again. Можно только к заливу.",
      tagline: "There is a light that never goes out.",
      tone: "sea",
      photo: "kotor",
      caption: "ещё не знаем, что это лучший день",
      summary:
        "Два часа — и город отпускает. Прогулка, еда, лодки, катер у Пераста. Крепость — вечером, когда жара простит, или оставить дыру в плёнке: не всё нужно досматривать.",
      drive: "Подгорица → Котор ~2 ч",
      hours: "весь день",
      color: "#1f6f6a",
      route: [
        [42.4415, 19.262],
        [42.39, 19.04],
        [42.4247, 18.7712],
        [42.4865, 18.699],
        [42.4257, 18.7728],
        [42.4185, 18.768],
      ],
      stops: [
        {
          id: "to-kotor",
          name: "Дорога в Котор",
          time: "утро",
          dur: "2 ч",
          kind: "drive",
          lat: 42.39,
          lng: 19.04,
          note: "Цетине или Созина — неважно. Важно не оглядываться на Подгорицу. Дорога — это жизнь, остальное — остановки.",
          maps: "https://www.google.com/maps/dir/Podgorica/Kotor",
        },
        {
          id: "kotor-walk",
          name: "Котор: прогулка и еда",
          time: "день",
          dur: "3 ч",
          kind: "walk",
          lat: 42.4247,
          lng: 18.7712,
          note: "Камень, который всех пережил. Кошки, которые никуда не уезжают. Есть медленно: это единственное, что нельзя перемотать.",
          maps: "https://www.google.com/maps/search/?api=1&query=Kotor+Old+Town",
        },
        {
          id: "boats",
          name: "Лодочки",
          time: "день",
          dur: "1 ч",
          kind: "boat",
          lat: 42.4247,
          lng: 18.768,
          note: "Маленький круг, как первая сторона кассеты: ещё не больно, уже красиво.",
          maps: "https://www.google.com/maps/search/?api=1&query=Kotor+boat+tour",
        },
        {
          id: "perast",
          name: "Катер у Пераста",
          time: "день",
          dur: "2 ч",
          kind: "boat",
          lat: 42.4865,
          lng: 18.699,
          note: "Остров на открытке. Госпожа Скальелли. Тот кадр, который потом будут просить «ещё раз» — а плёнка уже не та.",
          maps: "https://www.google.com/maps/search/?api=1&query=Perast+Montenegro",
        },
        {
          id: "fortress",
          name: "Kotor Fortress",
          time: "вечер / skip",
          dur: "2 ч",
          kind: "optional",
          lat: 42.4257,
          lng: 18.7728,
          note: "Ступеней много, как несказанных фраз. Лучше вечером — или честно забить. Не каждое прощание нужно поднимать наверх.",
          maps: "https://www.google.com/maps?cid=679848973021553970",
        },
        {
          id: "kotor-stay",
          name: "Ночёвка: Vidikovac",
          time: "с 15:00",
          dur: "94€",
          kind: "sleep",
          lat: 42.4185,
          lng: 18.768,
          note: "Vidikovac bb, 85330. С 15:00. Спать над заливом — значит просыпаться уже с тоской по сегодня.",
          maps: "https://www.google.com/maps/search/?api=1&query=Vidikovac+bb+85330+Kotor",
        },
      ],
    },
    {
      id: "sep7",
      date: "7 сентября",
      weekday: "понедельник",
      hwy: "03",
      track: "A3",
      slug: "EXT. ЛОВЧЕН — ПОЛДЕНЬ, КОТОРЫЙ УХОДИТ ВВЕРХ",
      title: "Fade into you — и в горы",
      quote: "Канатка красивая. Нам нужнее дорога, которая помнит руки на руле.",
      tagline: "Nothing gold can stay.",
      tone: "mountain",
      photo: "mist",
      caption: "туда, откуда не пишут открытки",
      summary:
        "Догулять Котор, пока он ещё наш. Ловчен — если сердце тянет вверх: мавзолей на Езерски, Alpine Coaster на Kuk. Потом север. Жабляк — да. Ночь — в Шавнике, тише, чем финал.",
      drive: "Котор → Ловчен → Никшич → Шавник ~3 ч",
      hours: "день уходит в горы",
      color: "#7a4a2b",
      route: [
        [42.4247, 18.7712],
        [42.395, 18.7954],
        [42.3994, 18.8383],
        [42.7731, 18.9445],
        [42.9564, 19.0967],
      ],
      stops: [
        {
          id: "kotor-encore",
          name: "Догулять Котор",
          time: "утро",
          dur: "1–2 ч",
          kind: "walk",
          lat: 42.4247,
          lng: 18.7712,
          note: "То, что вчера не влезло. Кофе. Последний взгляд — он всегда кажется недостаточным.",
          maps: "https://www.google.com/maps/search/?api=1&query=Kotor+Old+Town",
        },
        {
          id: "lovcen",
          name: "Ловчен",
          time: "день",
          dur: "по желанию",
          kind: "optional",
          lat: 42.399,
          lng: 18.819,
          note: "Хотим ли? Если да — на машине. Канатка для открытки. Серпантин — для тех, кто ещё не разучился прощаться медленно.",
          maps: "https://maps.app.goo.gl/HmC5aavW2n3Qk1mz6",
        },
        {
          id: "njegos",
          name: "Мавзолей Негоша, Езерски врх",
          time: "день",
          dur: "1–1.5 ч",
          kind: "vista",
          lat: 42.3994,
          lng: 18.8383,
          note: "Ветер выговаривает то, что мы не успеем. Весь залив внизу — как жизнь, которую видно только издалека.",
          maps: "https://maps.app.goo.gl/cTLpg5XYaRJvk4B7A",
        },
        {
          id: "coaster",
          name: "Alpine Coaster",
          time: "день",
          dur: "аттракцион",
          kind: "fun",
          lat: 42.395,
          lng: 18.7954,
          note: "Kuk. Можно без гондолы — к парковке. Одна глупая радость среди всех правильных прощаний.",
          maps: "https://maps.app.goo.gl/Ly3vkEzetHJf9N6h7?g_st=ic",
        },
        {
          id: "niksic",
          name: "Остановка в Никшиче",
          time: "вечер",
          dur: "кофе / бензин",
          kind: "drive",
          lat: 42.7731,
          lng: 18.9445,
          note: "Пауза между актами. Город, который никто не ставит на обложку — и поэтому он честный.",
          maps: "https://www.google.com/maps/search/?api=1&query=Nik%C5%A1i%C4%87",
        },
        {
          id: "zabljak-q",
          name: "Едем в Жабляк?",
          time: "вечер",
          dur: "~3 ч с Ловчена",
          kind: "drive",
          lat: 43.1547,
          lng: 19.1231,
          note: "Да. С Ловчена это не крюк — это судьба маршрута. Спать будем в Шавнике: ближе к тишине, чем к открытке.",
          maps: "https://www.google.com/maps/dir/Kotor/%C5%A0avnik",
        },
        {
          id: "savnik-1",
          name: "Ночёвка в Шавнике",
          time: "ночь",
          dur: "7–8 сен",
          kind: "sleep",
          lat: 42.9564,
          lng: 19.0967,
          note: "Narodnih Heroja, 81450. Здесь ночь длиннее песни. Утром — чёрная вода.",
          maps: "https://www.google.com/maps/search/?api=1&query=Narodnih+Heroja+81450+%C5%A0avnik",
        },
      ],
    },
    {
      id: "sep8",
      date: "8 сентября",
      weekday: "вторник",
      hwy: "04",
      track: "B1",
      slug: "EXT. ДУРМИТОР — УТРО, КОТОРОЕ НЕ ШУМИТ",
      title: "Озеро, где выключают голоса",
      quote: "How can it be? How can it be? Мы всё равно идём вокруг.",
      tagline: "Nightswimming, worth it every time.",
      tone: "lake",
      photo: "lake",
      caption: "вода, которая не отдаёт отражения",
      summary:
        "Чёрное озеро по кругу — тихий акт. Савин Кук, если небо не предаст. Мост Джурджевича. Каньон Тары. Ночь снова в Шавнике: некоторые места нужно оставлять дважды, чтобы поверить.",
      drive: "Шавник ⇄ Жабляк / Тара",
      hours: "полный день в парке",
      color: "#2b5f3a",
      route: [
        [42.9564, 19.0967],
        [43.1435, 19.0935],
        [43.1194, 19.0872],
        [43.1506, 19.2953],
        [42.9564, 19.0967],
      ],
      stops: [
        {
          id: "black-lake",
          name: "Черное озеро",
          time: "утро",
          dur: "петля пешком",
          kind: "walk",
          lat: 43.1435,
          lng: 19.0935,
          note: "Тропа вокруг — как повтор любимого куплета. Не пропускать. Потом уже будет слишком широко, чтобы шептать.",
          maps: "https://maps.google.com/?cid=13665381862594639599",
        },
        {
          id: "savin-kuk",
          name: "Канатная дорога Савин Кук",
          time: "день",
          dur: "подъём",
          kind: "vista",
          lat: 43.1194,
          lng: 19.0872,
          note: "Если небо чистое — Дурмитор покажет всё сразу, без жалости. Если нет — тоже правда.",
          maps: "https://www.google.com/maps/dir/%C5%BDabljak,+Montenegro/Savin+Kuk",
        },
        {
          id: "tara-bridge",
          name: "Мост Джурджевича",
          time: "день",
          dur: "фото + головокружение",
          kind: "vista",
          lat: 43.1506,
          lng: 19.2953,
          note: "Стоять над пустотой и не шутить. Некоторые виды просят тишины громче любой песни.",
          maps: "https://maps.app.goo.gl/vrDU6uWtJNZSxHa78",
        },
        {
          id: "tara-canyon",
          name: "Tara River Canyon",
          time: "день",
          dur: "смотрины",
          kind: "vista",
          lat: 43.152,
          lng: 19.27,
          note: "Камера врёт в меньшую сторону. Вживую понимаешь: мы маленькие, и это на сегодня утешение.",
          maps: "https://maps.app.goo.gl/7SzGoBLp57VbNCxVA",
        },
        {
          id: "savnik-2",
          name: "Снова Шавник",
          time: "ночь",
          dur: "8–9 сен",
          kind: "sleep",
          lat: 42.9564,
          lng: 19.0967,
          note: "Narodnih Heroja, 81450. Завтра самый длинный трек. Сегодня — дослушать тишину до конца.",
          maps: "https://www.google.com/maps/search/?api=1&query=Narodnih+Heroja+81450+%C5%A0avnik",
        },
      ],
    },
    {
      id: "sep9",
      date: "9 сентября",
      weekday: "среда",
      hwy: "05",
      track: "B2",
      slug: "EXT. КОЛЬЦО — ВЕСЬ ДЕНЬ, ПОКА НЕ КОНЧИТСЯ ПЛЁНКА",
      title: "Самый автомобильный день",
      quote: "And at once I knew I was not magnificent. Только дорога — да.",
      tagline: "Holocene. Окна вниз.",
      tone: "ring",
      photo: "durmitor",
      caption: "перевал, где кончаются слова",
      summary:
        "Жабляк, P14, перевал Седло, кольцо с остановками, которые нельзя планировать. Плужине. Пива. Потом трасса на Подгорицу — как выдох после долгой песни.",
      drive: "кольцо + Пива + Никшич → Подгорица",
      hours: "весь день за рулём",
      color: "#c45c26",
      route: [
        [43.1547, 19.1231],
        [43.0985, 19.051],
        [43.11, 18.98],
        [43.1528, 18.8397],
        [43.08, 18.85],
        [42.7731, 18.9445],
        [42.478, 19.268],
      ],
      stops: [
        {
          id: "from-zabljak",
          name: "Старт: Жабляк",
          time: "утро",
          dur: "P14 → M2",
          kind: "drive",
          lat: 43.1547,
          lng: 19.1231,
          note: "Бензин, вода, молчание. Дальше не нужно режиссёра. Хватит тех, кто сидит рядом.",
          maps: "https://www.google.com/maps/search/?api=1&query=%C5%BDabljak",
        },
        {
          id: "sedlo",
          name: "Перевал Седло",
          time: "утро",
          dur: "1907 м",
          kind: "vista",
          lat: 43.0985,
          lng: 19.051,
          note: "Самый высокий автомобильный перевал страны. Ветер, овцы, тишина как саундтрек. Здесь не фотографируют — здесь замолкают.",
          maps: "https://maps.app.goo.gl/h7yiXoaHdtrnRuAh9",
        },
        {
          id: "ring",
          name: "Дурмиторское кольцо P14",
          time: "день",
          dur: "остановки на фото",
          kind: "drive",
          lat: 43.11,
          lng: 18.98,
          note: "Не гнать. Каждые десять минут — новый постер, который нельзя увезти. Это и есть фильм. Это и есть прощание.",
          maps: "https://maps.app.goo.gl/89CmYSDr8HJs6SLf9",
        },
        {
          id: "pluzine",
          name: "Плужине и Пивское озеро",
          time: "день",
          dur: "смотрины",
          kind: "vista",
          lat: 43.1528,
          lng: 18.8397,
          note: "Вода цвета того, что нельзя назвать. Изумруд, глубина, плотина. Смотреть, пока не начнёт болеть.",
          maps: "https://maps.app.goo.gl/vDJCpRtovZPcF6tZ8",
        },
        {
          id: "piva",
          name: "Дорога вдоль Пивского каньона",
          time: "день",
          dur: "E762 к Никшичу",
          kind: "drive",
          lat: 43.08,
          lng: 18.85,
          note: "Узко, медленно, без права спешить. Потом Никшич — и выдох, который кажется предательством красоты.",
          maps: "https://www.google.com/maps/dir/Plu%C5%BEine/Nik%C5%A1i%C4%87",
        },
        {
          id: "home-run",
          name: "Никшич → Подгорица",
          time: "вечер",
          dur: "отличная трасса",
          kind: "drive",
          lat: 42.6,
          lng: 19.05,
          note: "Современная дорога после каньона — как титры на чёрном. Можно ехать спокойно. Уже почти больно.",
          maps: "https://www.google.com/maps/dir/Nik%C5%A1i%C4%87/Podgorica",
        },
        {
          id: "smokovac",
          name: "Ночёвка: Smokovac",
          time: "ночь",
          dur: "9–10 сен",
          kind: "sleep",
          lat: 42.478,
          lng: 19.268,
          note: "Smokovac BB, 80000. Последняя ночь на земле этой поездки. Утром — Скадар. Вечером — небо.",
          maps: "https://www.google.com/maps/search/?api=1&query=Smokovac+BB+Podgorica",
        },
      ],
    },
    {
      id: "sep10",
      date: "10 сентября",
      weekday: "четверг",
      hwy: "06",
      track: "B5",
      slug: "EXT. ПОСЛЕДНИЙ СВЕТ — ДО ТИТРОВ",
      title: "Не прощай. Просто выключи свет.",
      quote: "Well it's all right. Даже когда не все право.",
      tagline: "End of the line. Не гулять по столице.",
      tone: "finale",
      photo: "village",
      caption: "река, которая всё равно уйдёт в озеро",
      summary:
        "Подгорица как город — skip. Павлова страна, Липская пещера, «Ниагара». Машину вернуть. В 21:00 уже можно ехать в аэропорт. Вылет около 22:00. Кассета кончается раньше, чем хочется.",
      drive: "запад → пещера → Ниагара → аэропорт",
      hours: "день до 21:00",
      color: "#8b3a4a",
      route: [
        [42.478, 19.268],
        [42.3558, 19.0325],
        [42.36678, 18.95308],
        [42.3836, 19.2792],
        [42.3594, 19.2519],
      ],
      stops: [
        {
          id: "pg-skip",
          name: "Прогулка по Подгорице",
          time: "нет",
          dur: "skip",
          kind: "skip",
          lat: 42.441,
          lng: 19.262,
          note: "Не нужна. Столица подождёт другой жизни — той, где мы уже не эти.",
          maps: "https://www.google.com/maps/search/?api=1&query=Podgorica",
        },
        {
          id: "pavlova",
          name: "Павлова страна",
          time: "утро",
          dur: "фото-стоп",
          kind: "vista",
          lat: 42.3558,
          lng: 19.0325,
          note: "Подкова реки. Самый открыточный кадр, который всё равно не передашь. You had to be there. Мы будем.",
          maps: "https://maps.app.goo.gl/Gb9DBmsBafJwysrp8",
        },
        {
          id: "lipska",
          name: "Липская пещера",
          time: "день",
          dur: "~1 ч тур",
          kind: "walk",
          lat: 42.36678,
          lng: 18.95308,
          note: "У Цетине. Прохлада, камень, чужой голос гида. Уточнить слоты. Спуститься, пока ещё можно вернуться.",
          maps: "https://maps.app.goo.gl/pjLws2rUyCF2S6rR8",
        },
        {
          id: "niagara",
          name: "«Ниагара» (водопад Циевна)",
          time: "день",
          dur: "коротко",
          kind: "vista",
          lat: 42.3836,
          lng: 19.2792,
          note: "Близко к аэропорту. После дождей — громче. Летом может быть только шёпот. Оба варианта — правда.",
          maps: "https://maps.app.goo.gl/jfwDKXSxe18SzbqY9",
        },
        {
          id: "return-car",
          name: "Вернуть машину",
          time: "вечер",
          dur: "до вылета",
          kind: "tip",
          lat: 42.3594,
          lng: 19.2519,
          note: "Не впритык: бак, осмотр, очередь. Ключи отдают раньше, чем готов сердце. Потом — уже без руля.",
          maps: "https://www.google.com/maps/search/?api=1&query=car+rental+Podgorica+Airport",
        },
        {
          id: "airport-out",
          name: "Аэропорт",
          time: "с 21:00",
          dur: "вылет ~22:00",
          kind: "arrive",
          lat: 42.3594,
          lng: 19.2519,
          note: "В 21 уже можно ехать. Don't walk away in silence. Просто нажми stop. THE END.",
          maps: "https://www.google.com/maps/search/?api=1&query=Podgorica+Airport",
        },
      ],
    },
  ],
  stays: [
    {
      nights: "5–6 сентября",
      place: "Подгорица",
      address: "Vukosava Božovića bb, 81000",
      extra: "Первая ночь. Ещё не умеем скучать.",
      price: null,
      checkin: "по прилёту",
    },
    {
      nights: "6–7 сентября",
      place: "Котор",
      address: "Vidikovac bb, 85330 Kotor",
      extra: "Спать над заливом. Просыпаться уже с тоской.",
      price: "94€",
      checkin: "с 15:00",
    },
    {
      nights: "7–9 сентября",
      place: "Шавник",
      address: "Narodnih Heroja, 81450 Šavnik",
      extra: "Две ночи. Чтобы поверить, что тишина настоящая.",
      price: null,
      checkin: "две ночи подряд",
    },
    {
      nights: "9–10 сентября",
      place: "Подгорица · Smokovac",
      address: "Smokovac BB, 80000 Podgorica",
      extra: "Последняя ночь. Утром — река. Вечером — небо.",
      price: null,
      checkin: "после кольца",
    },
  ],
};
