window.TRIP = {
  title: "The Montenegro Tapes",
  dates: "5–10 сентября 2026",
  runtime: "6 дней",
  km: "~650 км",
  mixtape: [
    { n: "A1", title: "Born to Run", artist: "Bruce Springsteen" },
    { n: "A2", title: "Mr. Brightside", artist: "The Killers" },
    { n: "A3", title: "Float On", artist: "Modest Mouse" },
    { n: "A4", title: "The Middle", artist: "Jimmy Eat World" },
    { n: "A5", title: "Kids", artist: "MGMT" },
    { n: "B1", title: "Fast Car", artist: "Tracy Chapman" },
    { n: "B2", title: "Holocene", artist: "Bon Iver" },
    { n: "B3", title: "Home", artist: "Edward Sharpe" },
    { n: "B4", title: "Electric Feel", artist: "MGMT" },
    { n: "B5", title: "End of the Line", artist: "Traveling Wilburys" },
  ],
  photos: {
    road: "images/hero.jpg",
    kotor: "images/kotor.jpg",
    bay: "images/perast.jpg",
    mountain: "images/mountain.jpg",
    lake: "images/lake.jpg",
    canyon: "images/canyon.jpg",
    pass: "images/durmitor.jpg",
    forest: "images/forest.jpg",
    night: "images/night.jpg",
    village: "images/meadow.jpg",
    mist: "images/mist.jpg",
    durmitor: "images/durmitor.jpg",
    perast: "images/perast.jpg",
  },
  days: [
    {
      id: "sep5",
      date: "5 сентября",
      weekday: "суббота",
      hwy: "01",
      slug: "INT. АЭРОПОРТ ПОДГОРИЦЫ — НОЧЬ",
      title: "Прилёт. Машина. Мотель.",
      tagline: "Кассета только что встала в магнитолу.",
      tone: "night",
      photo: "night",
      caption: "golden hour где-то завтра",
      summary:
        "21:20 — касание полосы. Город уже тёмный, а утро нельзя тратить на прокат. Берём машину сегодня.",
      drive: "Подгорица",
      hours: "ночь",
      color: "#c45c26",
      stops: [
        {
          id: "airport",
          name: "Аэропорт Подгорица (TGD)",
          time: "21:20",
          dur: "прилёт",
          kind: "arrive",
          lat: 42.3594,
          lng: 19.2519,
          note: "Чемоданы, тёплый воздух, первая сигарета роуд-муви (метафорическая).",
          maps: "https://www.google.com/maps/search/?api=1&query=Podgorica+Airport",
        },
        {
          id: "car",
          name: "Забрать машину",
          time: "вечер",
          dur: "сейчас, не утром",
          kind: "tip",
          lat: 42.3594,
          lng: 19.2519,
          note: "По хорошему взять сразу: с 6-го утра уже дорога на Котор, а не очередь в прокате.",
          maps: "https://www.google.com/maps/search/?api=1&query=car+rental+Podgorica+Airport",
        },
        {
          id: "pg-stay",
          name: "Ночёвка в Подгорице",
          time: "ночь",
          dur: "5–6 сен",
          kind: "sleep",
          lat: 42.4415,
          lng: 19.262,
          note: "Vukosava Božovića bb, Подгорица, 81000. Короткий сон. Завтра — залив.",
          maps: "https://www.google.com/maps/search/?api=1&query=Vukosava+Bo%C5%BEovi%C4%87a+bb+Podgorica",
        },
      ],
    },
    {
      id: "sep6",
      date: "6 сентября",
      weekday: "воскресенье",
      hwy: "02",
      slug: "EXT. КОТОРСКИЙ ЗАЛИВ — ДЕНЬ",
      title: "Первый настоящий кадр",
      tagline: "Два часа серпантина — и вода становится кино.",
      tone: "sea",
      photo: "kotor",
      caption: "Котор, как на постере",
      summary:
        "Подгорица → Котор. Прогулка, еда, лодки, катер у Пераста. Крепость — вечером или честно забить: ступеней много, а день и так длинный.",
      drive: "Подгорица → Котор ~2 ч",
      hours: "весь день",
      color: "#1f6f6a",
      stops: [
        {
          id: "to-kotor",
          name: "Дорога в Котор",
          time: "утро",
          dur: "2 ч",
          kind: "drive",
          lat: 42.39,
          lng: 19.04,
          note: "Через Цетине или туннель Созина — как получится. Главное не застрять в Подгорице.",
          maps: "https://www.google.com/maps/dir/Podgorica/Kotor",
        },
        {
          id: "kotor-walk",
          name: "Котор: прогулка и еда",
          time: "день",
          dur: "3 ч",
          kind: "walk",
          lat: 42.4247,
          lng: 18.7712,
          note: "Старый город, кошки, камень, который помнит всех туристов. Есть не торопясь.",
          maps: "https://www.google.com/maps/search/?api=1&query=Kotor+Old+Town",
        },
        {
          id: "boats",
          name: "Лодочки",
          time: "день",
          dur: "1 ч",
          kind: "boat",
          lat: 42.4247,
          lng: 18.768,
          note: "Маленький круг по бухте. Разминка перед катером.",
          maps: "https://www.google.com/maps/search/?api=1&query=Kotor+boat+tour",
        },
        {
          id: "perast",
          name: "Катер у Пераста",
          time: "день",
          dur: "2 ч",
          kind: "boat",
          lat: 42.4865,
          lng: 18.699,
          note: "Госпожа Скальелли и остров на открытке. Это тот самый кадр из фильма.",
          maps: "https://www.google.com/maps/search/?api=1&query=Perast+Montenegro",
        },
        {
          id: "fortress",
          name: "Kotor Fortress",
          time: "вечер / skip",
          dur: "2 ч",
          kind: "optional",
          lat: 42.4257,
          lng: 18.7728,
          note: "Много ступеней. Лучше вечером, когда спадёт жара — или честно забить и оставить для сиквела.",
          maps: "https://www.google.com/maps?cid=679848973021553970",
        },
        {
          id: "kotor-stay",
          name: "Ночёвка: Vidikovac",
          time: "с 15:00",
          dur: "94€",
          kind: "sleep",
          lat: 42.4185,
          lng: 18.768,
          note: "Vidikovac bb, 85330 Kotor. Заезд с 15:00 — вписаться между морем и крепостью.",
          maps: "https://www.google.com/maps/search/?api=1&query=Vidikovac+bb+85330+Kotor",
        },
      ],
    },
    {
      id: "sep7",
      date: "7 сентября",
      weekday: "понедельник",
      hwy: "03",
      slug: "EXT. ЛОВЧЕН — ПОЛДЕНЬ",
      title: "Серпантин, мавзолей, север",
      tagline: "Канатка красивая. Машина — выгоднее. И правда роуд-муви.",
      tone: "mountain",
      photo: "mist",
      caption: "серпантин на Ловчен",
      summary:
        "Догуливаем Котор. Ловчен по желанию: мавзолей Негоша на Езерски, Alpine Coaster на Kuk. Потом — на Жабляк через Никшич, ночёвка в Шавнике.",
      drive: "Котор → Ловчен → Никшич → Шавник ~3 ч",
      hours: "день уходит в горы",
      color: "#7a4a2b",
      stops: [
        {
          id: "kotor-encore",
          name: "Догулять Котор",
          time: "утро",
          dur: "1–2 ч",
          kind: "walk",
          lat: 42.4247,
          lng: 18.7712,
          note: "То, что вчера не влезло в кадр. Кофе. Последний взгляд на залив.",
          maps: "https://www.google.com/maps/search/?api=1&query=Kotor+Old+Town",
        },
        {
          id: "lovcen",
          name: "Ловчен",
          time: "день",
          dur: "по желанию",
          kind: "optional",
          lat: 42.399,
          lng: 18.819,
          note: "Хотим ли? Если да — на машине, не на канатке: так дешевле и это та самая дорога.",
          maps: "https://maps.app.goo.gl/HmC5aavW2n3Qk1mz6",
        },
        {
          id: "njegos",
          name: "Мавзолей Негоша, Езерски врх",
          time: "день",
          dur: "1–1.5 ч",
          kind: "vista",
          lat: 42.3994,
          lng: 18.8383,
          note: "Вершина, ветер, весь залив как на ладони. Ступени снова, но другие.",
          maps: "https://maps.app.goo.gl/cTLpg5XYaRJvk4B7A",
        },
        {
          id: "coaster",
          name: "Alpine Coaster",
          time: "день",
          dur: "аттракцион",
          kind: "fun",
          lat: 42.395,
          lng: 18.7954,
          note: "Станция Kuk, верх канатки. Можно доехать на машине к парковке Kuk — без билета на гондолу.",
          maps: "https://maps.app.goo.gl/Ly3vkEzetHJf9N6h7?g_st=ic",
        },
        {
          id: "niksic",
          name: "Остановка в Никшиче",
          time: "вечер",
          dur: "кофе / бензин",
          kind: "drive",
          lat: 42.7731,
          lng: 18.9445,
          note: "С Ловчена на север как раз через Никшич. Город-пауза между двумя актами фильма.",
          maps: "https://www.google.com/maps/search/?api=1&query=Nik%C5%A1i%C4%87",
        },
        {
          id: "zabljak-q",
          name: "Едем в Жабляк?",
          time: "вечер",
          dur: "~3 ч с Ловчена",
          kind: "drive",
          lat: 43.1547,
          lng: 19.1231,
          note: "Да — и с Ловчена это логичный ход. Ночёвка не в самом Жабляке, а в Шавнике: ближе, тише, утром рукой подать до Дурмитора.",
          maps: "https://www.google.com/maps/dir/Kotor/%C5%A0avnik",
        },
        {
          id: "savnik-1",
          name: "Ночёвка в Шавнике",
          time: "ночь",
          dur: "7–8 сен",
          kind: "sleep",
          lat: 42.9564,
          lng: 19.0967,
          note: "Narodnih Heroja, 81450 Šavnik. Горная тишина, утром — чёрное озеро.",
          maps: "https://www.google.com/maps/search/?api=1&query=Narodnih+Heroja+81450+%C5%A0avnik",
        },
      ],
    },
    {
      id: "sep8",
      date: "8 сентября",
      weekday: "вторник",
      hwy: "04",
      slug: "EXT. ДУРМИТОР — УТРО",
      title: "Озеро, канатка, мост",
      tagline: "Национальный парк делает всю операторскую работу за вас.",
      tone: "lake",
      photo: "lake",
      caption: "утро у воды",
      summary:
        "Черное озеро по кругу, канатка Савин Кук, мост Джурджевича, каньон Тары. Ночь снова в Шавнике.",
      drive: "Шавник ⇄ Жабляк / Тара",
      hours: "полный день в парке",
      color: "#2b5f3a",
      stops: [
        {
          id: "black-lake",
          name: "Черное озеро",
          time: "утро",
          dur: "петля пешком",
          kind: "walk",
          lat: 43.1435,
          lng: 19.0935,
          note: "Тропа вокруг озера — тот самый спокойный акт перед каньоном. Не пропускать.",
          maps: "https://maps.google.com/?cid=13665381862594639599",
        },
        {
          id: "savin-kuk",
          name: "Канатная дорога Савин Кук",
          time: "день",
          dur: "подъём",
          kind: "vista",
          lat: 43.1194,
          lng: 19.0872,
          note: "С Жабляка рукой подать. Если небо чистое — весь Дурмитор как раскадровка.",
          maps: "https://www.google.com/maps/dir/%C5%BDabljak,+Montenegro/Savin+Kuk",
        },
        {
          id: "tara-bridge",
          name: "Мост Джурджевича",
          time: "день",
          dur: "фото + головокружение",
          kind: "vista",
          lat: 43.1506,
          lng: 19.2953,
          note: "Арка над Тарой. Можно просто постоять. Можно не смотреть вниз.",
          maps: "https://maps.app.goo.gl/vrDU6uWtJNZSxHa78",
        },
        {
          id: "tara-canyon",
          name: "Tara River Canyon",
          time: "день",
          dur: "смотрины",
          kind: "vista",
          lat: 43.152,
          lng: 19.27,
          note: "Один из самых глубоких каньонов Европы. Камера не врёт, но всё равно врёт — вживую больше.",
          maps: "https://maps.app.goo.gl/7SzGoBLp57VbNCxVA",
        },
        {
          id: "savnik-2",
          name: "Снова Шавник",
          time: "ночь",
          dur: "8–9 сен",
          kind: "sleep",
          lat: 42.9564,
          lng: 19.0967,
          note: "Narodnih Heroja, 81450 Šavnik. Завтра самый автомобильный день.",
          maps: "https://www.google.com/maps/search/?api=1&query=Narodnih+Heroja+81450+%C5%A0avnik",
        },
      ],
    },
    {
      id: "sep9",
      date: "9 сентября",
      weekday: "среда",
      hwy: "05",
      slug: "EXT. ДУРМИТОРСКОЕ КОЛЬЦО — ВЕСЬ ДЕНЬ",
      title: "Самый автомобильный день",
      tagline: "P14. Перевал Седло. Пива. И трасса, которая наконец выдыхает.",
      tone: "ring",
      photo: "durmitor",
      caption: "Дурмитор, без слов",
      summary:
        "Жабляк → P14/M2 → перевал Седло → Дурмиторское кольцо с остановками на фото → Плужине и Пивское озеро → каньон Пивы → Никшич → современная трасса в Подгорицу.",
      drive: "кольцо + Пива + Никшич → Подгорица",
      hours: "весь день за рулём (это фича)",
      color: "#c45c26",
      stops: [
        {
          id: "from-zabljak",
          name: "Старт: Жабляк",
          time: "утро",
          dur: "P14 → M2",
          kind: "drive",
          lat: 43.1547,
          lng: 19.1231,
          note: "Заправиться, вода, плёнка в камере. Дальше дорога сама режиссирует.",
          maps: "https://www.google.com/maps/search/?api=1&query=%C5%BDabljak",
        },
        {
          id: "sedlo",
          name: "Перевал Седло",
          time: "утро",
          dur: "1907 м",
          kind: "vista",
          lat: 43.0985,
          lng: 19.051,
          note: "Самый высокий автомобильный перевал Черногории. Ветер. Овцы. Тишина как саундтрек.",
          maps: "https://maps.app.goo.gl/h7yiXoaHdtrnRuAh9",
        },
        {
          id: "ring",
          name: "Дурмиторское кольцо P14",
          time: "день",
          dur: "остановки на фото",
          kind: "drive",
          lat: 43.11,
          lng: 18.98,
          note: "Не гнать. Каждые десять минут — новый постер. Это и есть фильм.",
          maps: "https://maps.app.goo.gl/89CmYSDr8HJs6SLf9",
        },
        {
          id: "pluzine",
          name: "Плужине и Пивское озеро",
          time: "день",
          dur: "смотрины",
          kind: "vista",
          lat: 43.1528,
          lng: 18.8397,
          note: "Вода цвета бензина в лучшем смысле: изумруд, глубина, плотина.",
          maps: "https://maps.app.goo.gl/vDJCpRtovZPcF6tZ8",
        },
        {
          id: "piva",
          name: "Дорога вдоль Пивского каньона",
          time: "день",
          dur: "E762 к Никшичу",
          kind: "drive",
          lat: 43.08,
          lng: 18.85,
          note: "Узко, красиво, медленно. Потом Никшич — и выдох.",
          maps: "https://www.google.com/maps/dir/Plu%C5%BEine/Nik%C5%A1i%C4%87",
        },
        {
          id: "home-run",
          name: "Никшич → Подгорица",
          time: "вечер",
          dur: "отличная трасса",
          kind: "drive",
          lat: 42.6,
          lng: 19.05,
          note: "После каньона — современная дорога, как титры на чёрном фоне. Можно ехать спокойно.",
          maps: "https://www.google.com/maps/dir/Nik%C5%A1i%C4%87/Podgorica",
        },
        {
          id: "smokovac",
          name: "Ночёвка: Smokovac",
          time: "ночь",
          dur: "9–10 сен",
          kind: "sleep",
          lat: 42.478,
          lng: 19.268,
          note: "Smokovac BB, 80000 Podgorica. Север города. Завтра — Скадар и пещера, потом самолёт.",
          maps: "https://www.google.com/maps/search/?api=1&query=Smokovac+BB+Podgorica",
        },
      ],
    },
    {
      id: "sep10",
      date: "10 сентября",
      weekday: "четверг",
      hwy: "06",
      slug: "EXT. СКАДАР / ПОДГОРИЦА — ПОСЛЕДНИЙ СВЕТ",
      title: "Финал. Без прогулки по столице.",
      tagline: "Подгорица как город — skip. Подгорица как база — да.",
      tone: "finale",
      photo: "village",
      caption: "последний поворот реки",
      summary:
        "Павлова страна, Липская пещера, «Ниагара» на Циевне. Машину вернуть. В 21:00 уже можно катить в аэропорт. Вылет ~22:00.",
      drive: "запад → пещера → Ниагара → аэропорт",
      hours: "день до 21:00",
      color: "#8b3a4a",
      stops: [
        {
          id: "pg-skip",
          name: "Прогулка по Подгорице",
          time: "нет",
          dur: "skip",
          kind: "skip",
          lat: 42.441,
          lng: 19.262,
          note: "Не нужна. Правда. Столица подождёт другой жизни.",
          maps: "https://www.google.com/maps/search/?api=1&query=Podgorica",
        },
        {
          id: "pavlova",
          name: "Павлова страна",
          time: "утро",
          dur: "фото-стоп",
          kind: "vista",
          lat: 42.3558,
          lng: 19.0325,
          note: "Подкова Риеки Црноевича. Самый открыточный кадр Скадарского озера.",
          maps: "https://maps.app.goo.gl/Gb9DBmsBafJwysrp8",
        },
        {
          id: "lipska",
          name: "Липская пещера",
          time: "день",
          dur: "~1 ч тур",
          kind: "walk",
          lat: 42.36678,
          lng: 18.95308,
          note: "У Цетине, ~35 км от Подгорицы. Прохлада, камень, гид. Уточнить слоты заранее.",
          maps: "https://maps.app.goo.gl/pjLws2rUyCF2S6rR8",
        },
        {
          id: "niagara",
          name: "«Ниагара» (водопад Циевна)",
          time: "день",
          dur: "коротко",
          kind: "vista",
          lat: 42.3836,
          lng: 19.2792,
          note: "Близко к городу и к аэропорту. После дождей — мощнее. Летом может быть скромнее.",
          maps: "https://maps.app.goo.gl/jfwDKXSxe18SzbqY9",
        },
        {
          id: "return-car",
          name: "Вернуть машину",
          time: "вечер",
          dur: "до вылета",
          kind: "tip",
          lat: 42.3594,
          lng: 19.2519,
          note: "Не впритык: бак, осмотр, очередь. Потом уже без руля.",
          maps: "https://www.google.com/maps/search/?api=1&query=car+rental+Podgorica+Airport",
        },
        {
          id: "airport-out",
          name: "Аэропорт",
          time: "с 21:00",
          dur: "вылет ~22:00",
          kind: "arrive",
          lat: 42.3594,
          lng: 19.2519,
          note: "В 21 уже можно ехать. Титры. THE END.",
          maps: "https://www.google.com/maps/search/?api=1&query=Podgorica+Airport",
        },
      ],
    },
  ],
  stays: [
    {
      nights: "5–6 сентября",
      place: "Подгорица",
      address: "Vukosava Božovića bb, 81000",
      extra: "Первая ночь. Машина уже наша.",
      price: null,
      checkin: "по прилёту",
    },
    {
      nights: "6–7 сентября",
      place: "Котор",
      address: "Vidikovac bb, 85330 Kotor",
      extra: "Вид на залив. Заезд не раньше трёх.",
      price: "94€",
      checkin: "с 15:00",
    },
    {
      nights: "7–9 сентября",
      place: "Шавник",
      address: "Narodnih Heroja, 81450 Šavnik",
      extra: "Две ночи. База под Дурмитор.",
      price: null,
      checkin: "две ночи подряд",
    },
    {
      nights: "9–10 сентября",
      place: "Подгорица · Smokovac",
      address: "Smokovac BB, 80000 Podgorica",
      extra: "Последняя ночь. Утром — Скадар, вечером — самолёт.",
      price: null,
      checkin: "после кольца",
    },
  ],
};

window.TRIP.route = [
  [42.3594, 19.2519],
  [42.4415, 19.262],
  [42.39, 19.04],
  [42.4247, 18.7712],
  [42.4865, 18.699],
  [42.4247, 18.7712],
  [42.395, 18.7954],
  [42.3994, 18.8383],
  [42.7731, 18.9445],
  [42.9564, 19.0967],
  [43.1547, 19.1231],
  [43.1435, 19.0935],
  [43.1194, 19.0872],
  [43.1506, 19.2953],
  [43.1547, 19.1231],
  [43.0985, 19.051],
  [43.11, 18.98],
  [43.1528, 18.8397],
  [43.08, 18.85],
  [42.7731, 18.9445],
  [42.478, 19.268],
  [42.3558, 19.0325],
  [42.36678, 18.95308],
  [42.3836, 19.2792],
  [42.3594, 19.2519],
];
