window.TRIP = {
  title: "МОНТЕНЕГРО",
  subtitle: "плёнка на шесть дней",
  dates: "5 — 10 сентября 2026",
  runtime: "6 дней",
  km: "~750 км",
  side: "SIDE A",
  epigraph: "Дальше — только дорога и то, что мы успеем запомнить.",
  epigraphSign: "— шесть дней, одна машина, полный багажник сентября",
  mixtape: [
    { n: "A1", title: "Приземление", artist: "5 сентября" },
    { n: "A2", title: "Которский залив", artist: "6 сентября" },
    { n: "A3", title: "Ловчен и длинный переезд", artist: "7 сентября" },
    { n: "A4", title: "Дурмитор", artist: "8 сентября" },
    { n: "A5", title: "Дурмиторское кольцо", artist: "9 сентября" },
    { n: "A6", title: "Конец плёнки", artist: "10 сентября" },
  ],
  photos: {
    road: "images/hero.jpg?v=uniq",
    kotor: "images/kotor.jpg?v=uniq",
    bay: "images/perast.jpg?v=uniq",
    mountain: "images/mountain.jpg?v=uniq",
    lake: "images/lake.jpg?v=uniq",
    canyon: "images/canyon.jpg?v=uniq",
    gorge: "images/gorge.jpg?v=uniq",
    pass: "images/pass.jpg?v=uniq",
    forest: "images/forest.jpg?v=uniq",
    night: "images/night.jpg?v=uniq",
    village: "images/rijeka.jpg?v=uniq",
    meadow: "images/meadow.jpg?v=uniq",
    mist: "images/mist.jpg?v=uniq",
    durmitor: "images/durmitor.jpg?v=uniq",
    perast: "images/perast.jpg?v=uniq",
    piva: "images/piva.jpg?v=uniq",
    njegos: "images/njegos.jpg?v=uniq",
    savin: "images/savin.jpg?v=uniq",
    airport: "images/airport.jpg?v=uniq",
    oldtown: "images/oldtown.jpg?v=uniq",
    serpentine: "images/serpentine.jpg?v=uniq",
    park: "images/park.jpg?v=uniq",
  },
  overview: {
    id: "overview",
    color: "#c45c26",
    title: "Шесть дней на одной стороне",
    slug: "РАЗВОРОТ ВКЛАДЫША",
    quote: "Дальше — только дорога и то, что мы успеем запомнить.",
    summary:
      "Шесть дней, около 750 километров и ни одного дня, когда мы не сидели бы в машине.",
    points: [
      {
        id: "ov-tgd",
        n: "01",
        name: "Аэропорт",
        place: "Подгорица · 21:20",
        lat: 42.3594,
        lng: 19.2519,
      },
      {
        id: "ov-pg",
        n: "02",
        name: "Подгорица",
        place: "первая ночь",
        lat: 42.4415,
        lng: 19.262,
      },
      {
        id: "ov-kotor",
        n: "03",
        name: "Котор",
        place: "залив, который держат горы",
        lat: 42.4247,
        lng: 18.7712,
      },
      {
        id: "ov-park",
        n: "04",
        name: "Дурмитор",
        place: "нацпарк · Жабляк",
        lat: 43.1547,
        lng: 19.1231,
      },
      {
        id: "ov-pg2",
        n: "05",
        name: "Подгорица",
        place: "последняя ночь",
        lat: 42.4415,
        lng: 19.262,
      },
      {
        id: "ov-out",
        n: "06",
        name: "Аэропорт",
        place: "вылет 22:00",
        lat: 42.3594,
        lng: 19.2519,
      },
    ],
  },
  days: [
    {
      id: "sep5",
      date: "5 сентября",
      weekday: "суббота",
      hwy: "01",
      track: "A1",
      slug: "Самолёт садится в 21:20. Лето ещё держится за крыло.",
      title: "Приземление",
      quote: "Дорогу осилит идущий.",
      tagline: "Самолёт садится в 21:20. Лето ещё держится за крыло.",
      tone: "night",
      photo: "night",
      caption: "тёплый асфальт, чужие голоса",
      summary: "Самолёт садится в 21:20. Лето ещё держится за крыло.",
      drive: "~15 км",
      hours: "ночь",
      color: "#c45c26",
      route: [
        [42.3594, 19.2519],
        [42.4415, 19.262],
      ],
      stops: [
        {
          id: "airport",
          name: "Прилёт в Подгорицу",
          time: "21:20",
          dur: "прилёт",
          kind: "arrive",
          photo: "airport",
          lat: 42.3594,
          lng: 19.2519,
          note: "Тёплый асфальт, чужие голоса, запах сосны и керосина. Всё ещё впереди.",
          maps: "https://www.google.com/maps/search/?api=1&query=Podgorica+Airport",
        },
        {
          id: "car",
          name: "Забрать машину сразу в аэропорту",
          time: "по-хорошему — вечером",
          dur: "сразу",
          kind: "tip",
          lat: 42.3594,
          lng: 19.2519,
          note: "Утро дороже денег: если взять ключи ночью, завтра не придётся отдавать морю два часа.",
          maps: "https://www.google.com/maps/search/?api=1&query=car+rental+Podgorica+Airport",
        },
        {
          id: "pg-stay",
          name: "Заселение, Подгорица",
          time: "ночь",
          dur: "5–6 сен",
          kind: "sleep",
          lat: 42.4415,
          lng: 19.262,
          note: "Vukosava Božovića bb. Первая ночь всегда самая короткая — её жалко тратить на сон.",
          maps: "https://www.google.com/maps/search/?api=1&query=Vukosava+Bo%C5%BEovi%C4%87a+bb+Podgorica",
        },
      ],
    },
    {
      id: "sep6",
      date: "6 сентября",
      weekday: "воскресенье",
      hwy: "02",
      track: "A2",
      slug: "Два часа серпантина — и город, который держат горы за плечи.",
      title: "Которский залив",
      quote: "Нельзя дважды войти в одну и ту же реку. — Гераклит",
      tagline: "Два часа серпантина — и город, который держат горы за плечи.",
      tone: "sea",
      photo: "kotor",
      caption: "город, который держат горы за плечи",
      summary: "Два часа серпантина — и город, который держат горы за плечи.",
      drive: "~110 км",
      hours: "весь день",
      color: "#1f6f6a",
      route: [
        [42.4415, 19.262],
        [42.39, 19.04],
        [42.4247, 18.7712],
        [42.4865, 18.699],
        [42.4257, 18.7728],
        [42.4185, 18.768],
      ],
      stops: [
        {
          id: "to-kotor",
          name: "Подгорица → Котор",
          time: "утро",
          dur: "2 ч",
          kind: "drive",
          lat: 42.39,
          lng: 19.04,
          note: "Первые окна вниз. Плейлист выбирает тот, кто сзади.",
          maps: "https://www.google.com/maps/dir/Podgorica/Kotor",
        },
        {
          id: "kotor-walk",
          name: "Старый город: прогулка и еда",
          time: "день",
          dur: "3 ч",
          kind: "walk",
          photo: "oldtown",
          lat: 42.4247,
          lng: 18.7712,
          note: "Заблудиться здесь — не ошибка, а часть маршрута. Кошки знают дорогу лучше нас.",
          maps: "https://www.google.com/maps/search/?api=1&query=Kotor+Old+Town",
        },
        {
          id: "boats",
          name: "Лодочки",
          time: "день",
          dur: "1 ч",
          kind: "boat",
          lat: 42.4262,
          lng: 18.7666,
          note: "Вода держит небо и не роняет.",
          maps: "https://www.google.com/maps/search/?api=1&query=Kotor+boat+tour",
        },
        {
          id: "perast",
          name: "Катер у Пераста — Госпа од Шкрпела",
          time: "день",
          dur: "2 ч",
          kind: "boat",
          photo: "perast",
          lat: 42.4869,
          lng: 18.6989,
          note: "Остров, который люди насыпали руками, камень за камнем, потому что очень хотели во что-то верить.",
          maps: "https://www.google.com/maps/search/?api=1&query=Perast+Montenegro",
        },
        {
          id: "fortress",
          name: "Крепость Святого Иоанна",
          time: "2 ч · ~1350 ступеней",
          dur: "по желанию",
          kind: "optional",
          photo: "mountain",
          lat: 42.4272,
          lng: 18.7756,
          note: "Лучше на закате — или забить и остаться внизу. Обе версии дня одинаково правильные.",
          maps: "https://www.google.com/maps?cid=679848973021553970",
        },
        {
          id: "kotor-stay",
          name: "Ночёвка: Vidikovac",
          time: "с 15:00",
          dur: "94 €",
          kind: "sleep",
          lat: 42.4185,
          lng: 18.768,
          note: "Vidikovac bb, 85330 Kotor. Заезд с 15:00.",
          maps: "https://www.google.com/maps/search/?api=1&query=Vidikovac+bb+85330+Kotor",
        },
      ],
    },
    {
      id: "sep7",
      date: "7 сентября",
      weekday: "понедельник",
      hwy: "03",
      track: "A3",
      slug: "Двадцать пять петель вверх — и залив складывается в открытку под ногами.",
      title: "Ловчен и длинный переезд",
      quote: "Гора с горой не сходится, а человек с человеком сойдётся.",
      tagline: "Двадцать пять петель вверх — и залив складывается в открытку под ногами.",
      tone: "mountain",
      photo: "serpentine",
      caption: "залив складывается в открытку под ногами",
      summary: "Двадцать пять петель вверх — и залив складывается в открытку под ногами.",
      drive: "~220 км",
      hours: "день уходит в горы",
      color: "#7a4a2b",
      route: [
        [42.4247, 18.7712],
        [42.395, 18.7954],
        [42.3994, 18.8383],
        [42.7731, 18.9445],
        [42.9564, 19.0967],
      ],
      stops: [
        {
          id: "kotor-encore",
          name: "Догулять Котор",
          time: "утро",
          dur: "утро",
          kind: "walk",
          lat: 42.4247,
          lng: 18.7712,
          note: "Города прощаются тише, чем люди.",
          maps: "https://www.google.com/maps/search/?api=1&query=Kotor+Old+Town",
        },
        {
          id: "coaster",
          name: "Alpine Coaster",
          time: "день",
          dur: "~30 мин",
          kind: "fun",
          lat: 42.4335,
          lng: 18.7889,
          note: "Тот самый кадр, который потом будет стоять на аватарке весь год.",
          maps: "https://maps.app.goo.gl/Ly3vkEzetHJf9N6h7",
        },
        {
          id: "lovcen",
          name: "Национальный парк Ловчен",
          time: "день",
          dur: "серпантин",
          kind: "vista",
          photo: "mist",
          lat: 42.4008,
          lng: 18.8375,
          note: "Канатка есть, но нам выгоднее машиной: на своих колёсах можно останавливаться где хочется.",
          maps: "https://maps.app.goo.gl/HmC5aavW2n3Qk1mz6",
        },
        {
          id: "njegos",
          name: "Мавзолей Негоша, Езерски врх",
          time: "день",
          dur: "461 ступень · 1657 м",
          kind: "vista",
          photo: "njegos",
          lat: 42.4008,
          lng: 18.8375,
          note: "Наверху ветер и вся страна разом. Отсюда видно даже то, куда мы ещё не доехали.",
          maps: "https://maps.app.goo.gl/cTLpg5XYaRJvk4B7A",
        },
        {
          id: "niksic",
          name: "Остановка в Никшиче",
          time: "кофе",
          dur: "кофе",
          kind: "drive",
          lat: 42.7731,
          lng: 18.9483,
          note: "Заправиться, размять ноги, поспорить, чья очередь за рулём.",
          maps: "https://www.google.com/maps/search/?api=1&query=Nik%C5%A1i%C4%87",
        },
        {
          id: "zabljak-q",
          name: "Переезд к Жабляку / Шавнику",
          time: "вечер",
          dur: "~3 ч",
          kind: "drive",
          lat: 42.9572,
          lng: 19.0958,
          note: "Последний час едем уже в темноте. Фары, серпантин, никого — и это лучшее, что было за день.",
          maps: "https://www.google.com/maps/dir/Kotor/%C5%A0avnik",
        },
        {
          id: "savnik-1",
          name: "Ночёвка в Шавнике",
          time: "ночь",
          dur: "7 и 8 сентября",
          kind: "sleep",
          lat: 42.9564,
          lng: 19.0967,
          note: "Narodnih Heroja, 81450 Šavnik. Ночи 7 и 8 сентября.",
          maps: "https://www.google.com/maps/search/?api=1&query=Narodnih+Heroja+81450+%C5%A0avnik",
        },
      ],
    },
    {
      id: "sep8",
      date: "8 сентября",
      weekday: "вторник",
      hwy: "04",
      track: "A4",
      slug: "Чёрное озеро с утра лежит как зеркало, в которое неловко смотреть.",
      title: "Дурмитор",
      quote: "Всё течёт, всё меняется. — Гераклит",
      tagline: "Чёрное озеро с утра лежит как зеркало, в которое неловко смотреть.",
      tone: "lake",
      photo: "park",
      caption: "вода цвета старой плёнки",
      summary: "Чёрное озеро с утра лежит как зеркало, в которое неловко смотреть.",
      drive: "~120 км",
      hours: "полный день в парке",
      color: "#2b5f3a",
      route: [
        [42.9564, 19.0967],
        [43.1435, 19.0935],
        [43.1194, 19.0872],
        [43.1506, 19.2953],
        [42.9564, 19.0967],
      ],
      stops: [
        {
          id: "black-lake",
          name: "Чёрное озеро",
          time: "утро",
          dur: "круговой маршрут ~3,5 км",
          kind: "walk",
          photo: "lake",
          lat: 43.1428,
          lng: 19.0925,
          note: "Сосны, тишина и вода цвета старой плёнки. Идти медленно — обязательное условие.",
          maps: "https://maps.google.com/?cid=13665381862594639599",
        },
        {
          id: "savin-kuk",
          name: "Канатная дорога Савин Кук",
          time: "день",
          dur: "2 ч",
          kind: "vista",
          photo: "savin",
          lat: 43.1333,
          lng: 19.0806,
          note: "Подъём над границей леса. Там уже пахнет осенью, хотя внизу ещё август.",
          maps: "https://www.google.com/maps/dir/%C5%BDabljak,+Montenegro/Savin+Kuk",
        },
        {
          id: "tara-bridge",
          name: "Мост Джурджевича",
          time: "день",
          dur: "~1 ч",
          kind: "vista",
          photo: "canyon",
          lat: 43.1503,
          lng: 19.2939,
          note: "150 метров пустоты под ногами. Все делают одно и то же фото — и правильно делают.",
          maps: "https://maps.app.goo.gl/vrDU6uWtJNZSxHa78",
        },
        {
          id: "tara-canyon",
          name: "Каньон реки Тара",
          time: "день",
          dur: "смотровые по дороге",
          kind: "vista",
          photo: "gorge",
          lat: 43.1512,
          lng: 19.35,
          note: "Второй по глубине каньон в мире. Река резала его миллион лет и до сих пор не закончила.",
          maps: "https://maps.app.goo.gl/7SzGoBLp57VbNCxVA",
        },
        {
          id: "savnik-2",
          name: "Снова Шавник",
          time: "ночь",
          dur: "вторая ночь",
          kind: "sleep",
          lat: 42.9564,
          lng: 19.0967,
          note: "Narodnih Heroja, 81450 Šavnik. Вторая ночь на том же месте.",
          maps: "https://www.google.com/maps/search/?api=1&query=Narodnih+Heroja+81450+%C5%A0avnik",
        },
      ],
    },
    {
      id: "sep9",
      date: "9 сентября",
      weekday: "среда",
      hwy: "05",
      track: "A5",
      slug: "Самый автомобильный день: 80 километров, которые едешь целый день и не жалеешь.",
      title: "Дурмиторское кольцо",
      quote: "Не бывает попутного ветра для того, кто не знает, куда плывёт. — Сенека",
      tagline: "Самый автомобильный день: 80 километров, которые едешь целый день и не жалеешь.",
      tone: "ring",
      photo: "durmitor",
      caption: "мы физически выше облаков",
      summary: "Самый автомобильный день: 80 километров, которые едешь целый день и не жалеешь.",
      drive: "~250 км",
      hours: "весь день за рулём",
      color: "#c45c26",
      route: [
        [43.1547, 19.1231],
        [43.0985, 19.051],
        [43.11, 18.98],
        [43.1528, 18.8397],
        [43.08, 18.85],
        [42.7731, 18.9445],
        [42.478, 19.268],
      ],
      stops: [
        {
          id: "from-zabljak",
          name: "Старт из Жабляка, дорога P14",
          time: "утро",
          dur: "утро",
          kind: "drive",
          lat: 43.1544,
          lng: 19.1222,
          note: "Термос, пыль на приборной панели, песня, которую все знают наизусть.",
          maps: "https://www.google.com/maps/search/?api=1&query=%C5%BDabljak",
        },
        {
          id: "sedlo",
          name: "Перевал Седло",
          time: "утро",
          dur: "1907 м",
          kind: "vista",
          photo: "pass",
          lat: 43.1236,
          lng: 19.0022,
          note: "Высшая точка дороги. Мы физически выше облаков — и никто в этот момент не смотрит в телефон.",
          maps: "https://maps.app.goo.gl/h7yiXoaHdtrnRuAh9",
        },
        {
          id: "ring",
          name: "Кольцо P14 с остановками на фото",
          time: "день",
          dur: "сколько захотим",
          kind: "drive",
          lat: 43.09,
          lng: 18.95,
          note: "Здесь нет неправильного места для остановки. Есть только те, где мы не остановились.",
          maps: "https://maps.app.goo.gl/89CmYSDr8HJs6SLf9",
        },
        {
          id: "pluzine",
          name: "Плужине и Пивское озеро",
          time: "день",
          dur: "бирюза",
          kind: "vista",
          photo: "piva",
          lat: 43.1536,
          lng: 18.8397,
          note: "Вода такого цвета, что кажется отфильтрованной. Она не отфильтрована.",
          maps: "https://maps.app.goo.gl/vDJCpRtovZPcF6tZ8",
        },
        {
          id: "piva",
          name: "Пивский каньон → Никшич (E762)",
          time: "день",
          dur: "56 тоннелей",
          kind: "drive",
          lat: 43.05,
          lng: 18.83,
          note: "Свет — темнота — свет. Как монтаж в кино, только с нами внутри.",
          maps: "https://www.google.com/maps/dir/Plu%C5%BEine/Nik%C5%A1i%C4%87",
        },
        {
          id: "home-run",
          name: "Никшич → Подгорица",
          time: "вечер",
          dur: "отличная трасса",
          kind: "drive",
          lat: 42.4304,
          lng: 19.2594,
          note: "Наконец-то ровный асфальт и можно молчать всю дорогу, ни разу не соскучившись.",
          maps: "https://www.google.com/maps/dir/Nik%C5%A1i%C4%87/Podgorica",
        },
        {
          id: "smokovac",
          name: "Ночёвка: Smokovac",
          time: "ночь",
          dur: "последняя ночь",
          kind: "sleep",
          lat: 42.478,
          lng: 19.268,
          note: "Smokovac BB, 80000 Podgorica. Последняя ночь.",
          maps: "https://www.google.com/maps/search/?api=1&query=Smokovac+BB+Podgorica",
        },
      ],
    },
    {
      id: "sep10",
      date: "10 сентября",
      weekday: "четверг",
      hwy: "06",
      track: "A6",
      slug: "Вылет в 22:00. У нас есть целый день, чтобы не думать об этом.",
      title: "Конец плёнки",
      quote: "Всё хорошее когда-нибудь кончается — но плёнку можно перемотать.",
      tagline: "Вылет в 22:00. У нас есть целый день, чтобы не думать об этом.",
      tone: "finale",
      photo: "village",
      caption: "река рисует петлю, будто ей тоже не хочется уезжать",
      summary: "Вылет в 22:00. У нас есть целый день, чтобы не думать об этом.",
      drive: "~140 км",
      hours: "день до 21:00",
      color: "#8b3a4a",
      route: [
        [42.478, 19.268],
        [42.3558, 19.0325],
        [42.36678, 18.95308],
        [42.3836, 19.2792],
        [42.3594, 19.2519],
      ],
      stops: [
        {
          id: "pg-skip",
          name: "Прогулка по Подгорице",
          time: "скорее нет, чем да",
          dur: "skip",
          kind: "skip",
          lat: 42.4304,
          lng: 19.2594,
          note: "Мы уже решили: город подождёт. В последний день едут туда, где красиво.",
          maps: "https://www.google.com/maps/search/?api=1&query=Podgorica",
        },
        {
          id: "pavlova",
          name: "Павлова страна — излучина Црноевича",
          time: "утро",
          dur: "смотровая",
          kind: "vista",
          photo: "meadow",
          lat: 42.3494,
          lng: 18.9339,
          note: "Река рисует петлю, будто ей тоже не хочется уезжать.",
          maps: "https://maps.app.goo.gl/Gb9DBmsBafJwysrp8",
        },
        {
          id: "lipska",
          name: "Липская пещера",
          time: "день",
          dur: "~1 ч · +10 °C",
          kind: "walk",
          photo: "forest",
          lat: 42.33,
          lng: 18.8636,
          note: "Внутри всегда одна и та же осень. Ей два миллиона лет, и ей всё равно, что мы улетаем.",
          maps: "https://maps.app.goo.gl/pjLws2rUyCF2S6rR8",
        },
        {
          id: "niagara",
          name: "Водопад «Ниагара» на Цијевне",
          time: "день",
          dur: "в сентябре — как повезёт",
          kind: "optional",
          lat: 42.3644,
          lng: 19.2247,
          note: "К концу лета он часто пересыхает. Тогда это просто камни и кафе с видом на то, что было весной.",
          maps: "https://maps.app.goo.gl/jfwDKXSxe18SzbqY9",
        },
        {
          id: "return-car",
          name: "Вернуть машину",
          time: "до 20:00",
          dur: "до 20:00",
          kind: "tip",
          lat: 42.3594,
          lng: 19.2519,
          note: "Достать из багажника песок, чеки и чужую толстовку.",
          maps: "https://www.google.com/maps/search/?api=1&query=car+rental+Podgorica+Airport",
        },
        {
          id: "airport-out",
          name: "В аэропорт — в 21:00",
          time: "21:00",
          dur: "вылет 22:00",
          kind: "arrive",
          lat: 42.3594,
          lng: 19.2519,
          note: "Плёнка домотана до конца и щёлкает вхолостую. Side B — когда-нибудь потом.",
          maps: "https://www.google.com/maps/search/?api=1&query=Podgorica+Airport",
        },
      ],
    },
  ],
  stays: [
    {
      nights: "ночь с 5 на 6 сентября",
      place: "Подгорица",
      address: "Vukosava Božovića bb, Подгорица, 81000",
      extra: "Первая ночь всегда самая короткая — её жалко тратить на сон.",
      price: null,
      checkin: "по прилёту",
    },
    {
      nights: "6–7 сентября",
      place: "Котор",
      address: "Vidikovac bb, 85330 Kotor",
      extra: "Спать над заливом.",
      price: "94 €",
      checkin: "заезд с 15:00",
    },
    {
      nights: "ночи 7 и 8 сентября",
      place: "Шавник",
      address: "Narodnih Heroja, 81450 Šavnik",
      extra: "Вторая ночь на том же месте.",
      price: null,
      checkin: "две ночи подряд",
    },
    {
      nights: "последняя ночь",
      place: "Подгорица · Smokovac",
      address: "Smokovac BB, 80000 Podgorica",
      extra: "Последняя ночь.",
      price: null,
      checkin: "после кольца",
    },
  ],
};
